# Machine Learning practico con la ayuda de Python
# Capitulo 3: Numpy

## Aldo Humberto Romero 

### BUAP, Marzo, 2022

## Configuracion

In [1]:
%load_ext watermark

In [2]:
%watermark

2020-05-30T13:38:24-04:00

CPython 3.7.7
IPython 7.13.0

compiler   : Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 19.5.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit


In [3]:
import numpy
%watermark -iv

numpy 1.18.1



## Numpy

Numpy es el corazon de las librerias de computacion cientifica de Python. Provee un arreglo multidimensional de alto rendimiento, ademas provee las herramientas para trabajar con estos arreglos.

Caracteristicas interesantes de Numpy:

 * **numpy** esta escriba en C y esta basada en los paquetes de operacion algebraica BLAS y LAPACK. 
 * **numpy** Es bastante mas rapida que otras librerias de Python que tambien trabajan con arreglos, especialmente cuando la comparamos con otras estructuras como listas, diccionarios, etc. 
 * **numpy** es la libreria base de muchas otras librerias en computacion cientifica y en ciencia de datos. 
 * **numpy** cuyo objecto fundamental es `numpy.ndarray` ejecuta todas las operaciones fundamentales como reformateo, ordenamiento, indexamiento, etc.


Para usar Numpy, lo primero que tenemos que hacer es importar el paquete Numpy.

In [2]:
import numpy as np

### Arreglos

Un arreglo de Numpy es in a cuadricula de valores, todos del mismo tipo es indexados por tuplas de enteros no negativos. El numero de dimensiones corresponde al rango del arreglo, la forma del arreglo es una tupla de enteros que nos da el tamaño de arreglo a lo largo de cada dimension.

Podemos inicializar los arreglos de Numpy a partir de listas de Python y accesar sus elementos usando parentesis cuadrados. 

In [2]:
a = np.array([1, 2, 3])  # Crea un arreglo de dimension 1
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Cambia un elemento del arreglo
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # Crea un arreglo de rango 2
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [7]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy nos da una seria de funciones que podemos usar para crear arreglos

In [3]:
a = np.zeros((2,2,2))  
print(a)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [4]:
b = np.ones((1,2))   
print(b)
print(b[0])

[[1. 1.]]
[1. 1.]


In [10]:
c = np.full((2,2), 7) 
print(c) 

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)       
print(d)

[[1. 0.]
 [0. 1.]]


In [6]:
print(4*[1,2,3])
d=np.repeat([1,2,3],4) # Crea una matrix 1x12 donde cada elemento esta repetido 4 veces
print(d.shape)
d1=np.array([1,2,3]*4) # Crea una matrix 1x12 donde cada vector es repetido 4 veces 
print(d)
print(d1)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
(12,)
[1 1 1 1 2 2 2 2 3 3 3 3]
[1 2 3 1 2 3 1 2 3 1 2 3]


In [4]:
d=np.ones((3,2)) 
print(d)
d1=np.vstack([d,2*d]) #  Crea una matrix apilando dos matrices 
print(d1)
d1=np.hstack([d,2*d]) # Crea una matrix a partir de dos (o mas), una al lado de la otra
print(d1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [1. 1. 2. 2.]]


In [5]:
e = np.random.random((2,2)) # Matrix llena de valores aleatorios
print(e)

[[0.53173605 0.189926  ]
 [0.81992109 0.50664288]]


### Indexamiento del arreglo

In [13]:
import numpy as np


a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Cortamos la matriz para crear un subareglo de las dos primeras filas y las columnas 1 y 2
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
b = a[:2, 0:3:2]  
print(b)
print(a[-1,::2]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[1 3]
 [5 7]]
[ 9 11]


Cambiando el "slice" no cambia el arreglo original

In [14]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 
print(b)

2
2
[[77  3]
 [ 5  7]]


Podemos mezclar la manera como indexamos usando enteros o "slice". 

In [15]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
row_r1 = a[1, :]    # Rango 1 de la segunda fila 
row_r2 = a[1:2, :]  # Rango 2 de la sebunda fila
row_r3 = a[[1], :]  
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [17]:
# Para columnas
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [18]:
# Ahora hagamos combinaciones interesantes

a = np.array([[1,2], [3, 4], [5, 6]])

# lo de abajo es equivalente a un vector con a[0,0],a[1,1],a[2,0]

print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [8]:
# Definamos una matrix pero hagamos algo diferente
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# Arreglo de indices
b = np.array([0, 2, 0, 1])

# Seleccion un elemento de cada fila usando los indices de b 
print(np.arange(4))
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[0 1 2 3]
[ 1  6  7 11]


Indexamiento usando valores booleanos o de logica. Usado cuando queremos seleccionar elementso que satisfacen alguna condicion. 

In [10]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Encuentra todos los elementos con eset condicion 

print(type(bool_idx))

print(bool_idx)

<class 'numpy.ndarray'>
[[False False]
 [ True  True]
 [ True  True]]


In [20]:
# Podemos ahora usar este arreglo para construir un arreglo de rango 1 que consiste
# de los elementos de a que son "ciertos" a esta condicion
print(a[bool_idx])

#O usando tambien:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


### Tipos de Datos

Cada arreglo de Numpy es una grid de elementios del mismo tipo> numpy trata de encontrar el tipo de datos que le daran al final al tipo de arreglo, pero los metodos para crear arreglos tambien nos permiten definir el tipo

In [8]:
x = np.array([1, 2])  # Numpy escoge el tipo de datos
y = np.array([1., 2])  # 
p = np.array(['a',1])
z = np.array([1, 2], dtype=np.int64)  # Forzamos el tipo de datos 
w = np.array([1, 2], dtype=np.float64)  # Forzamos el tipo de datos 

print(type(x))
print(x.dtype, y.dtype, p.dtype, z.dtype, w.dtype)

<class 'numpy.ndarray'>
int64 float64 <U21 int64 float64


Puedes leer mas acerca de los tipos de datos en [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Matematica de los arreglos

Funciones matematicas basicas en arreglos Numpy operan en los elementos de los arreglos y puedes hacerse con "operadores" o con funciones. 

In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Suma element por elemento 
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [23]:
# Diferencia
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [24]:
# Producto
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [25]:
# Division
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
# Raiz cuadrada
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto punto o producto interior 
print(v.shape,w.shape)
print(v.dot(w))
print(np.dot(v, w))

(2,) (2,)
219
219


In [19]:
# Multiplicacion 
print(x.shape,v.shape)
print(x.dot(v))
print(v.dot(x))
print(np.dot(x, v))
print(np.dot(x.T, v)) # con la traspuesta de x

(2, 2) (2,)
[29 67]
[39 58]
[29 67]
[39 58]


In [33]:
# Producto Matriz / matriz product
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [31]:
print(x.dtype)
x=x.astype('f')
print(x.dtype)

int64
float32


Numpy nos da un gran numero de funciones para operar en arreglos, uno de ellos es la `sum`

In [32]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Suma de todos los elementos
print(np.sum(x, axis=0))  # suma de las columnas; imprime "[4 6]"
print(np.sum(x, axis=1))  # suma de las filas; imprime "[3 7]"

10
[4 6]
[3 7]


In [11]:
x = np.array([[-1,2],[3,-4]])
print(x)
print(x.mean())
print(x.std())
print(x.sum())
print('Min = ',x.min(),x.argmin())
print(x.max(),x.argmax())
print(x**2)

[[-1  2]
 [ 3 -4]]
0.0
2.7386127875258306
0
Min =  -4 3
3 2
[[ 1  4]
 [ 9 16]]


La lista de las funciones matematicas la encuentra aqui [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Ademas de las funciones matematicas, nosotros tambien podemos o cambiar su "forma" or  manipular su contenido, por ejemplo su transpuesta es x.T

In [34]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [35]:
v = np.array([[1,2,3]])
print(v) 
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


Podemos crear arreglos que este distribuidos uniformement. Una donde espeficamos el comienzo, el final y tamaño de la estapa o definiendo el minimo, el maximo y el numero de numeros que se desean en ese intervalo.

In [36]:
a=np.arange(0,10,2)
print(a)
b=np.linspace(0,10,8)
print(b)

[0 2 4 6 8]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


#### Copiando arreglos

In [37]:
a=np.arange(20)
a.resize((4,5))
print(a)
a[a>8]=30   # Poniendo el maximo del arreglo a 30 
print(a)

# copiamos un "slice" de a en r
r=a[:2,:2]
print(r)
#Asignamos 0 a todos los elementos de r 
r[:]=0
# Veamos que cambio
print(a)
print(r)
#  Si queremos copiar el arreglo original 
a=np.arange(20)
a.resize((4,5))
r=a[:2,:2].copy()
r[:]=0
print(a)
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]
[[0 1]
 [5 6]]
[[ 0  0  2  3  4]
 [ 0  0  7  8 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]
[[0 0]
 [0 0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 0]
 [0 0]]


#### Iterando sobre el arreglo

In [12]:
x=np.random.randint(1,20,(4,5))
print(x)
for i in x:
    print(i)
for i,r in enumerate(x):
    print(i,r)
for i in range(4):
    for j in range(5):
        print(i,j,x[i,j])

[[19  6  3 12  8]
 [12  1  5  3  4]
 [16  3 10 17  6]
 [18  1 18 10 15]]
[19  6  3 12  8]
[12  1  5  3  4]
[16  3 10 17  6]
[18  1 18 10 15]
0 [19  6  3 12  8]
1 [12  1  5  3  4]
2 [16  3 10 17  6]
3 [18  1 18 10 15]
0 0 19
0 1 6
0 2 3
0 3 12
0 4 8
1 0 12
1 1 1
1 2 5
1 3 3
1 4 4
2 0 16
2 1 3
2 2 10
2 3 17
2 4 6
3 0 18
3 1 1
3 2 18
3 3 10
3 4 15


In [39]:
y=np.random.randint(1,20,(4,5))
print(y)

for i,j in zip(x,y):
    print(i+j)

[[17  9 17  5 15]
 [ 3  5 10 13  4]
 [ 5 11 11  7 14]
 [ 4 15 14 15  5]]
[34 24 24 13 26]
[16 12 26 31 11]
[17 14 26  9 18]
[22 30 26 33 22]


## Vectorizacion

In [40]:
import time 
x=np.random.rand(1000000)
y=np.random.rand(1000000)

tic=time.time()
z=np.dot(x,y)
toc=time.time()
print('Result =',z)

print("Vectorized = "+str(1000*(toc-tic))+" ms")

z=0.0
tic=time.time()
for i in range(1000000):
    z += x[i]*y[i]
toc=time.time()
print('Result =',z)

print("Non Vectorized = "+str(1000*(toc-tic))+" ms")

Result = 249933.4008241569
Vectorized = 0.6468296051025391 ms
Result = 249933.4008241592
Non Vectorized = 201.1120319366455 ms


CPI y GPU tiene lo que llaman SIMD (single instructions, multiple data) y Numpy toma ventaja de esto. En GPU es inclusive mejor. Lo importante para tener en mente es que uno debe evitar "loops" or bocles tanto como sea posible.

In [41]:
# Multiplicacion Vector-Matrix

import time 

x=np.random.rand(1000)
y=np.random.rand(1000,1000)

tic=time.time()
z=np.dot(x,y)
toc=time.time()


print("Vectorized = "+str(1000*(toc-tic))+" ms")

#Exponential over a vector

tic=time.time()
z=np.exp(x)
toc=time.time()

print("Vectorized = "+str(1000*(toc-tic))+" ms")


Vectorized = 2.8328895568847656 ms
Vectorized = 0.053882598876953125 ms


Numpy tiene muchas diferentes funciones que pueden ser usados en vectorizacion, operaciones como log, abs, maxmium, operaciones por elemento (v**2), etc. 

### Broadcasting

In [13]:
A=np.array([[12.0,0.0,8.0,5.0],[4.8,3.2,1.4,2.5],[1.2,8.0,1.2,3.2]])
print(A)
sum_columns=np.sum(A,axis=0)
print(sum_columns)
print(sum_columns.shape)

# Divida cada columna por la suma de toda la columna 
# Aqui, el "braodcasting" lo que hace es dividir la matrix A, pero cada columna se divide por numero diferente

d=sum_columns.reshape(1,4)
print(d.shape)
percentage=100*A/sum_columns.reshape(1,4)

print(percentage)

percentage=100*A/sum_columns

print(percentage)

[[12.   0.   8.   5. ]
 [ 4.8  3.2  1.4  2.5]
 [ 1.2  8.   1.2  3.2]]
[18.  11.2 10.6 10.7]
(4,)
(1, 4)
[[66.66666667  0.         75.47169811 46.72897196]
 [26.66666667 28.57142857 13.20754717 23.36448598]
 [ 6.66666667 71.42857143 11.32075472 29.90654206]]
[[66.66666667  0.         75.47169811 46.72897196]
 [26.66666667 28.57142857 13.20754717 23.36448598]
 [ 6.66666667 71.42857143 11.32075472 29.90654206]]


Broadcasting es un mecanismo poderoso que permite a numpy a trabajar con arreglos de diferentes tamaños y realizar operaciones aritmeticas. Por ejemplo, frecuentemente tenemos un arreglo pequeño y uno mas grande y lo que queremos es usar el arreglo pequeño varias veces para hacer alguna operacion en el arreglo mas grande.

Por ejemplo, sumar un vector constante a cada columan de una matrix

In [43]:
#
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x.shape)
v = np.array([1, 0, 1])
print(v.shape)
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

(4, 3)
(3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Esto va bien, aunque viene a ser lento si el tamaño de la matrix `x` es muy grande. Una manera es "generar" una matrix donde pegamos copias del vector `v` y luego hacer la suma elemento por elemento. 

EN realidad Python hace esto por su cuenta: 

In [40]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Si te parece complicado, te recomienda leer [documentacion](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or tutoriales [tutorial_1](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/), [tutorial_2](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/).

Las funciones que soportan estas operaciones lo pueden encontrar en la [documentacion](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Por ejemplo:

In [44]:
# Calcular el "outer product" de vectores 
v = np.array([1,2,3])  # v tiene dimension (3,)
w = np.array([4,5])    # w tiene dimension (2,)

print(v)
print(w)

# para calcular este prouecto, primero redimensionamos v a un vector columna de (3,1)
# y luego lo "broadcast" con w, para tener un vector de dimension (3,2)


print(np.reshape(v, (3, 1)) * w)

[1 2 3]
[4 5]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [45]:
# sumar un vector a una matrix

x = np.array([[1,2,3], [4,5,6]])

print(x + v)

[[2 4 6]
 [5 7 9]]


In [47]:
# Sumar un vector a cada columna de una matrix 
# x tiene dimension (2, 3) y w tiene dimension (2,).
# si transponemos x, tiene la dimension (3, 2) y luego hacer el broadcast

print(x.shape)
print(w.shape)
print((x.T + w).T)

(2, 3)
(2,)
[[ 5  6  7]
 [ 9 10 11]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

Antes de terminar, veamos algunos detalles acerca de vectores que no es trivial en Python

In [48]:
a=np.random.rand(8)
print(a)
print(a.shape)

[0.94436879 0.84305321 0.69188816 0.9439572  0.52102152 0.21170585
 0.73420167 0.88725629]
(8,)


Como ven, la dimension no es (8,1) o (1,8) pero es (8,), este vector es de rango uno pero no se considera ni columna ni fila. Veamos los efectos

In [49]:
print(np.dot(a,a.T))
print(np.dot(a,a))

4.614894158993276
4.614894158993276


Compare a

In [50]:
a=np.random.rand(8,1)
print(a)

print(np.dot(a,a.T))
print(a.shape)
print(np.dot(a,a))
print(np.dot(a.T,a))


[[0.89933975]
 [0.03814989]
 [0.8525365 ]
 [0.7195104 ]
 [0.95942891]
 [0.23438204]
 [0.22728905]
 [0.69590371]]
[[0.80881199 0.03430971 0.76671996 0.64708431 0.86285256 0.21078908
  0.20441008 0.62585387]
 [0.03430971 0.00145541 0.03252417 0.02744924 0.03660211 0.00894165
  0.00867105 0.02654865]
 [0.76671996 0.03252417 0.72681848 0.61340888 0.81794816 0.19981924
  0.19377221 0.59328331]
 [0.64708431 0.02744924 0.61340888 0.51769522 0.69031908 0.16864031
  0.16353684 0.50070996]
 [0.86285256 0.03660211 0.81794816 0.69031908 0.92050384 0.2248729
  0.21806769 0.66767014]
 [0.21078908 0.00894165 0.19981924 0.16864031 0.2248729  0.05493494
  0.05327247 0.16310733]
 [0.20441008 0.00867105 0.19377221 0.16353684 0.21806769 0.05327247
  0.05166031 0.15817129]
 [0.62585387 0.02654865 0.59328331 0.50070996 0.66767014 0.16310733
  0.15817129 0.48428197]]
(8, 1)


ValueError: shapes (8,1) and (8,1) not aligned: 1 (dim 1) != 8 (dim 0)

Por lo tanto, a menos que sepas lo que estes haciendo, siempre es mejor tener claridad sobre la forma del vector, mantengala (8,1) por ejemplo. Para mirar si es la dimensionalidad puedes usar

```
assert(a.shape==(8,1))
```
y puedes cambiar las dimensiones usando

```
a.reshape((1,8))
```